### ISSUE TITLE
imagemin-pngcrush not building correctly

### ISSUE THREAD

**Issue by namelivia** [mcasimir/generator-mobileangularui#11]
Hello everyone, I've created a new application, installed everything, built it an everything was ok.
When modifying the app I inserted an image in the images folder and after that the gulp build task was failing. It seems that the pngcrush binary was not ok and could not be executed:

"bash: ./pngcrush: cannot execute binary file"

I've done npm uninstall imagemin-pngcrush and right after npm install imagemin-pngcrush and now everything is working.

**Comment by namelivia** [comment]
Not sure if related, now for the 'images' gulp task to finish I have to comment this block:
```
 stream = stream.pipe(imagemin({
        progressive: true,
        svgoPlugins: [{removeViewBox: false}],
        use: [pngcrush()]
    }));
```
Even if I set config.minify_images to false, the task dies if that lines of code are not commented.

**Comment by RemcovandenBerg** [comment]
Hi there, I couldn't reproduce the error, but I am on Windows. 
It's looking like a permission error. Does it still happen when running with `sudo` ?

**Comment by mcasimir** [comment]
@namelivia In current release i've dropped image minification at all, due it was causing too many issues.
