### ISSUE TITLE
Error on creating project

### ISSUE THREAD

**Issue by datatrancend2015** [mcasimir/generator-mobileangularui#12]
I tried to install it, it works fine but when i run "yo mobileangularui". i end with this error.
![asd](https://cloud.githubusercontent.com/assets/11168553/6680290/1c1e2d00-cc90-11e4-80ad-d16dd4b91d45.png)

help me please. thanks

**Comment by RemcovandenBerg** [comment]
Looks like a common problem with npm and roaming. It is not in our project. https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
