### ISSUE TITLE
Ftp upload error

### ISSUE THREAD

**Issue by swapnilsg** [mcasimir/generator-mobileangularui#13]
can any body help me to solve this issue,i get this when i try to upload file to ftp server
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)

**Comment by RemcovandenBerg** [comment]
This question out of the scope of this project. Not sure what program you are using to upload. But it looks like a connection error (wrong address / authentication issues etc.).
Please find help where they can actually help you.
