### ISSUE TITLE
generator wont install

### ISSUE THREAD

**Issue by drkhannah** [mcasimir/generator-mobileangularui#15]
wont install

ohbocmb3g3qd:~ hannade$ sudo npm install -g generator-mobileangularui
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-mobileangularui will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> buffertools@2.1.2 install /usr/local/lib/node_modules/generator-mobileangularui/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
  SOLINK_MODULE(target) Release/buffertools.node: Finished
 
> unicode@0.6.1 postinstall /usr/local/lib/node_modules/generator-mobileangularui/node_modules/slug/node_modules/unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
request timed out.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-mobileangularui"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hannade/npm-debug.log
ohbocmb3g3qd:~ hannade$ cordova --version
5.0.0
ohbocmb3g3qd:~ hannade$ sudo npm install -g generator-mobileangularui
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-mobileangularui will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> buffertools@2.1.2 install /usr/local/lib/node_modules/generator-mobileangularui/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
  SOLINK_MODULE(target) Release/buffertools.node: Finished
 
> unicode@0.6.1 postinstall /usr/local/lib/node_modules/generator-mobileangularui/node_modules/slug/node_modules/unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
request timed out.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-mobileangularui"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hannade/npm-debug.log

**Comment by mcasimir** [comment]
@drkhannah 

```
npm install -g yo gulp bower
```

and then just

```
yo
```

You will be prompted with different options, one should be `Install a generator`

![yo](https://cloud.githubusercontent.com/assets/334881/9064219/c153f5ee-3acb-11e5-9328-49ab35931ab7.png)

Try that.

**Comment by starr749** [comment]
I'm pretty sure the problem here is with the unicode package, which is required by slug.

I would try a `npm install -g slug` or `npm install -g unicode` to see if you get the exact same error.

One workaround If you're using a unix based system is to create the path `/usr/share/unicode/` and download this file ->  http://unicode.org/Public/UNIDATA/UnicodeData.txt  into it.

If you're stuck on a windows machine, I'm pretty sure you need to be able to download the file, and this error is caused by you being behind a proxy. In which case you need to set your HTTP_PROXY environment variable.

**Comment by ilife5** [comment]
A simpler way.

U can download unicodeData.txt and put it in any folder.

Then install like this:

```
NODE_UNICODETABLE_UNICODEDATA_TXT=/{$yourpath}/UnicodeData.txt  npm install -g generator-mobileangularui
```

**Comment by brunodacunha** [comment]
running these commands worked for me

```
# debian
sudo apt-get install unicode-data # optional
# gentoo
sudo emerge unicode-data # optional
npm install unicode
```
