### ISSUE TITLE
Load css files under bower_components library

### ISSUE THREAD

**Issue by ccalabro** [mcasimir/generator-mobileangularui#16]
Hi. I add an angular-ui slider and I need to load a css file of jquery-ui library. In the config.js you can attach a js file, using config.vendor.js.push, but you can't attach a css file. How can I do this?. Thanks.

**Comment by mcasimir** [comment]
@ccalabro Basically the best/cleanest way would be to use a less import to require your css files. Given css is well formed and does not contains strange characters it would work fine as long as less is a superset of css.

On other projects I use `gulp-concat` to merge css together, you can try to concat some css files to compiled less sources editing `gulpfile.js`. But it is far simpler to use the less approach.
