### ISSUE TITLE
Upgrade Font Awesome to 4.3

### ISSUE THREAD

**Issue by aroller** [mcasimir/generator-mobileangularui#17]
bower.json has a dependency reference to "font-awesome": "4.2" and there is a 4.3 release available. I tried to update on my app and received an error when running gulp:

>  at new Parser /... /node_modules/less/lib/less/parser.js:333:27

I'm not a power user when it comes to bower, less or other of these web build technologies so I am unable to provide much help.

**Comment by mcasimir** [comment]
@aroller This is much more of a `mobile-angular-ui` issue itself where Font Awesome dependency is defined.
