### ISSUE TITLE
'mobile-angular-ui/src/less/mobile-angular-ui.less' wasn't found. 

### ISSUE THREAD

**Issue by rbellec** [mcasimir/generator-mobileangularui#21]
Hi, just after following initial instruction I had this error 

    gulp build

    /Users/my_user_dir/Documents/Travail/phonegap/weather/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
    throw e;
    		      ^
    Error: 'mobile-angular-ui/src/less/mobile-angular-ui.less' wasn't found. 
    [...]
    in file /Users/my_user_dir/Documents/Travail/phonegap/weather/src/less/app.less line no. 1

I found that there was no file `mobile-angular-ui.less`, only `mobile-angular-ui-base.less`, `mobile-angular-ui-desktop.less`, `mobile-angular-ui-migrate.less` in mobile-angular-ui.

I changed `app.less` to import `mobile-angular-ui-base.less` which works. I don't know if this is the right file to use. Maybe the app.less generator or the instruction should reflect this change.

**Comment by mcasimir** [comment]
Hi @rbellec,
thank u very much for reporting this. That's interesting, probably this won't work with current release. Will check and let U know.

**Comment by mcasimir** [comment]
yep you're right, this won't work with current release. Going to fix immediately. Thank u very much!

**Comment by sarathraj-coder** [comment]
getting same error

**Comment by sarathraj-coder** [comment]
C:\Users\Administrator\angularui\app\node_modules\gulp-less\node_modules\accord\
node_modules\when\lib\decorators\unhandledRejection.js:80
                throw e;
                      ^
Error: 'mobile-angular-ui/src/less/mobile-angular-ui-base.less' wasn't found. Tr
ied - C:\Users\Administrator\angularui\app\src\less\mobile-angular-ui\src\less\m
obile-angular-ui-base.less,C:\Users\Administrator\angularui\app\src\less\mobile-
angular-ui\src\less\mobile-angular-ui-base.less,C:\Users\Administrator\angularui
\app\bower_components\mobile-angular-ui\src\less\mobile-angular-ui-base.less,mob
ile-angular-ui\src\less\mobile-angular-ui-base.less in file C:\Users\Administrat
or\angularui\app\src\less\app.less line no. 1

**Comment by mcasimir** [comment]
Please update your generator. https://travis-ci.org/mcasimir/generator-mobileangularui

**Comment by turbowars** [comment]
@sarathraj-coder where you able to update your generator?

**Comment by laranicolas** [comment]
@mcasimir How can I update mobileangularui generator without overwrite old files?

**Comment by sarathraj-coder** [comment]
1) First you can install node using nvm . Personally i am using ubundu .
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps

   // install the latest version  check the above link , below command to list the available versions of node 
   $nvm ls-remote

2) Git must be configured 
3) npm -g install bower
4) npm install -g yo gulp generator-mobileangularui
5   npm install -g cordova
6) npm install -g phonegap
7) then create your project and run the application using gulp / cordova run andoid/ cordova run ios . In this cases you must confugred the JAVA, Android tool etc .. 
     In case of IOS xcode and IOS emualtor is conigured

**Comment by sarathraj-coder** [comment]
SRC folder contains all , take a copy and reuse it again in the new project

**Comment by laranicolas** [comment]
@sarathraj-coder thanks for response, those are the step for initiate a generator, so the only way is copying files from generator directory to project directory checking each filile when replace.
