### ISSUE TITLE
how we can create ,edit existing and new css and js 

### ISSUE THREAD

**Issue by sarathraj-coder** [mcasimir/generator-mobileangularui#22]
Hi ,  
       i am deleaing with a new project and trying to evaluate the system , so how we can create a new html template ,editing css using the generator

**Comment by mcasimir** [comment]
You can customize HTML template as you wish. For the css, the preferred way is to use less. (basically is the same than customizing bootstrap).

Soon i will provide a way to use themes from https://bootswatch.com/.
