### ISSUE TITLE
bower ENORESTARGET  No tag found that was able to satisfy 1.2.x

### ISSUE THREAD

**Issue by sarathraj-coder** [mcasimir/generator-mobileangularui#23]
I am getting error when running "yo mobileangularui" .

error is :
bower ENORESTARGET  No tag found that was able to satisfy 1.2.x

**Comment by mcasimir** [comment]
Hi @sarathraj-coder, i'm not able to replicate. What version of the generator are you running? On which platform (OS, npm version). 

https://travis-ci.org/mcasimir/generator-mobileangularui

**Comment by sarathraj-coder** [comment]
Hi am using windows with below npm and node versions

C:\Users\Administrator\angularui>node -v
v0.12.7

C:\Users\Administrator\angularui>npm -v
2.11.3

**Comment by sarathraj-coder** [comment]
thanks ,above link worked fine . But used the latest node version . 

I am using phone gap for application development , how i can use the updated version in phone-gap ..

**Comment by sarathraj-coder** [comment]
thanks ,above link worked fine . But used the latest node version .
