### ISSUE TITLE
Another error on gulp build: font-awesome less files missing 

### ISSUE THREAD

**Issue by RichSnei** [mcasimir/generator-mobileangularui#7]
I'm running into a similar error to the one reported in October.
I'm running on Windows (don't know if it makes a different) using git bash.  

$ gulp build
[13:53:24] Using gulpfile c:\SvnCXDSrc\weather\gulpfile.js
[13:53:24] Starting 'build'...
[13:53:24] Starting 'clean'...
[13:53:24] Finished 'clean' after 19 ms
[13:53:24] Starting 'html'...
[13:53:24] Finished 'html' after 1.71 ms
[13:53:24] Starting 'fonts'...
[13:53:24] Starting 'images'...
[13:53:24] Starting 'less'...
[13:53:24] Finished 'less' after 4.15 ms
[13:53:24] Starting 'js'...
[13:53:24] Finished 'js' after 12 ms
[13:53:24] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[13:53:24] Finished 'images' after 25 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 'font-awesome/less/spinning.less' wasn't found in file c:\SvnCXDSrc\weather\bower_components\mobile-angular-ui\src\less\mobile-angular-ui.less line no. 18

**Comment by TonyMtz** [comment]
Hello, RichSnei!
This is because some changes on font-awesome. You can skip this error changing the version of font-awesome in your bower.json to 4.2. Cheers.

**Comment by leolux** [comment]
Still the same error...
bower.json:
{
  "name": "testmaui",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "angular": "1.x",
    "angular-route": "1.x",
    "mobile-angular-ui": "1.2.x",
    "font-awesome": "4.2",
    "bootstrap": "3.x"
  }
}

**Comment by ccnp123** [comment]
I have this same issue. I didn't try messing with the font-awesome version like @leolux, for now, I just commented out the line `@import "font-awesome/less/spinning"` in the file `bower_components/mobile-angular-ui/src/less/mobile-angular-ui.less`.

This lets me `gulp build` (or `gulp less`) without errors.

I suppose if I need a spinning icon I can just add it myself.

**Comment by maxboal** [comment]
I have the same Issue. Thanks @ccnp123 it worked.

**Comment by tshelburne** [comment]
@ccnp123 @maxboal @leolux Setting it to 4.2 worked for me - my bower looks like this:

```
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "angular": "1.x",
    "angular-route": "1.x",
    "mobile-angular-ui": "1.2.x",
    "font-awesome": "4.2",
    "bootstrap": "3.x"
  }
}
```

**Comment by RemcovandenBerg** [comment]
Same issue as mcasimir/mobile-angular-ui#226. Fixed so issue van be closed.

**Comment by flight212121** [comment]
Thanks, I was using yeoman generators for angular and setting "font-awesome": "4.2" fixed my issue as well.
